# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-28 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fox.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partition', models.CharField(max_length=50)),
                ('used', models.IntegerField()),
                ('use', models.IntegerField(default=0)),
                ('capacity', models.IntegerField()),
                ('available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('hostname', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('mem_total', models.CharField(max_length=50)),
                ('disk', models.CharField(max_length=50)),
                ('cpu_version', models.CharField(default='Xeon', max_length=50)),
                ('product', models.CharField(default='Dell', max_length=50)),
                ('sn', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HostTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.FloatField(default='100', verbose_name=fox.models.Task)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_task', to='fox.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(verbose_name='内存大小（MB)')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_mem', to='fox.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('name', models.CharField(default='Cron', max_length=32, primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=32)),
                ('status', models.FloatField(default='1')),
            ],
        ),
        migrations.AddField(
            model_name='hosttask',
            name='task',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='fox.Task'),
        ),
        migrations.AddField(
            model_name='disk',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_disk', to='fox.Host'),
        ),
    ]
