# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-01 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='100%', max_length=6),
        ),
    ]
