# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-16 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='sn',
            field=models.CharField(default='xxxxx', max_length=40),
        ),
    ]
