# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-01 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fox', '0002_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.FloatField(default='1', max_length=6),
        ),
    ]
