# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-16 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fox', '0002_host_sn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='id',
        ),
        migrations.AlterField(
            model_name='host',
            name='sn',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
