# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-01 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fox', '0003_auto_20170601_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='host',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=32),
        ),
    ]
