# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-16 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fox', '0003_auto_20170616_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='product',
            field=models.CharField(default='Dell', max_length=50),
        ),
    ]
