# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-16 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fox', '0004_host_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='cpu_version',
            field=models.CharField(default='Xeon', max_length=50),
        ),
    ]
