# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-01 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fox', '0005_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default='cron', max_length=32, primary_key=True, serialize=False),
        ),
    ]
