# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-20 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fox', '0005_host_cpu_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partition', models.CharField(max_length=50)),
                ('used', models.IntegerField(max_length=10)),
                ('capacity', models.IntegerField(max_length=10)),
                ('available', models.IntegerField(max_length=10)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_disk', to='fox.Host')),
            ],
        ),
    ]
