# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-01 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fox', '0006_auto_20170601_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default='Cron', max_length=32),
        ),
    ]
