# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-21 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fox', '0006_disk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='available',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='disk',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='disk',
            name='used',
            field=models.IntegerField(),
        ),
    ]
