# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-23 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fox', '0007_auto_20170621_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='use',
            field=models.IntegerField(default=0),
        ),
    ]
