# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-01 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fox', '0009_remove_hosttask_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosttask',
            name='task',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='fox.Task'),
        ),
    ]
