# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-06 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fox', '0011_hosttask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.FloatField(default='1'),
        ),
    ]
