# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-06 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import fox.models


class Migration(migrations.Migration):

    dependencies = [
        ('fox', '0012_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosttask',
            name='status',
            field=models.FloatField(default='100', verbose_name=fox.models.Task),
        ),
    ]
